prepare-artifacts-dir:
  stage: prepare
  script:
    - ssh builder@mobian-project.org mkdir -p ${ARTIFACTS_ROOT}/${CI_PIPELINE_ID}

cleanup-artifacts-dir:
  stage: cleanup
  script:
    - ssh builder@mobian-project.org rm -rf ${ARTIFACTS_ROOT}/${CI_PIPELINE_ID}
  when: always

.save-artifacts: &save-artifacts |
  scp ${MOBIAN_ARTIFACTS} builder@mobian-project.org:${ARTIFACTS_ROOT}/${CI_PIPELINE_ID}

.restore-artifacts: &restore-artifacts |
  for artifact in ${MOBIAN_ARTIFACTS}; do
    scp builder@mobian-project.org:${ARTIFACTS_ROOT}/${CI_PIPELINE_ID}/${artifact} .
  done

.define-upload-location: &define-upload-location |
  if [ "${CI_PIPELINE_SOURCE}" = "schedule" ]; then
    IMAGES_DIR=${IMAGES_ROOT}/${MOBIAN_DEVICE_NAME}/nightly
  else
    IMAGES_DIR=${IMAGES_CI_ROOT}/$(date --date="${CI_PIPELINE_CREATED_AT}" +%Y%m%d.%H%M)
  fi

.upload-images: &upload-images |
  ssh builder@mobian-project.org mkdir -p ${IMAGES_DIR}
  for image in ${MOBIAN_IMAGES}; do
    scp ${image} builder@mobian-project.org:${IMAGES_DIR}/
  done

.finish-images: &finish-images |
  if [ -f "${IMAGE_NAME}.img" ]; then
    bmaptool create "${IMAGE_NAME}.img" > "${IMAGE_NAME}.img.bmap"
    gzip --force ${IMAGE_NAME}.img
    sha256sum ${IMAGE_NAME}.img.gz ${IMAGE_NAME}.img.bmap > ${IMAGE_NAME}.sha256sums
  elif [ -f ${IMAGE_NAME}.root.img ]; then
    tar czf ${IMAGE_NAME}.tar.gz ${IMAGE_NAME}.boot-*.img ${IMAGE_NAME}.root.img
    rm ${IMAGE_NAME}.boot-*.img ${IMAGE_NAME}.root.img
    sha256sum ${IMAGE_NAME}.tar.gz > ${IMAGE_NAME}.sha256sums
  fi

.rootfs-generic:
  stage: rootfs
  script:
    - MOBIAN_ARTIFACTS="rootfs-${ARCH}-${MOBIAN_GRAPHICAL_SHELL}.tar.gz"
    - debos --scratchsize=8G
      -t architecture:${ARCH}
      -t environment:${MOBIAN_GRAPHICAL_SHELL}
      -t nonfree:${MOBIAN_INCLUDE_NONFREE}
      -t debian_suite:${DEBIAN_SUITE}
      -t suite:${MOBIAN_SUITE}
      -t rootfs:${MOBIAN_ARTIFACTS}
      rootfs.yaml
    - *save-artifacts

.rootfs-installer:
  stage: rootfs
  script:
    - debos --scratchsize=8G
      -t architecture:${ARCH}
      installfs.yaml
    - MOBIAN_ARTIFACTS="installfs-${ARCH}.tar.gz"
    - *save-artifacts

.devicefs:
  stage: devicefs
  script:
    - MOBIAN_ARTIFACTS="rootfs-${ARCH}-${MOBIAN_GRAPHICAL_SHELL}.tar.gz"
    - *restore-artifacts
    - debos --scratchsize=8G
      -t architecture:${ARCH}
      -t environment:${MOBIAN_GRAPHICAL_SHELL}
      -t device:${MOBIAN_DEVICE_NAME}
      -t family:${MOBIAN_DEVICE_FAMILY}
      -t nonfree:${MOBIAN_INCLUDE_NONFREE}
      -t rootfs:${MOBIAN_ARTIFACTS}
      rootfs-device.yaml
    - MOBIAN_ARTIFACTS="rootfs-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}.tar.gz"
    - *save-artifacts

.image:
  stage: image
  script:
    - MOBIAN_ARTIFACTS="rootfs-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}.tar.gz"
    - *restore-artifacts
    - IMAGE_NAME=mobian-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}-$(date --date="${CI_PIPELINE_CREATED_AT}" +%Y%m%d)
    - debos --scratchsize=8G
      -t architecture:${ARCH}
      -t environment:${MOBIAN_GRAPHICAL_SHELL}
      -t device:${MOBIAN_DEVICE_NAME}
      -t family:${MOBIAN_DEVICE_FAMILY}
      -t filesystem:${MOBIAN_FILESYSTEM}
      -t image:${IMAGE_NAME}
      -t imagesize:${MOBIAN_IMAGE_SIZE}
      -t partitiontable:${MOBIAN_PARTITION_TABLE}
      image.yaml
    - *finish-images
    - MOBIAN_IMAGES="mobian-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}-*"
    - *define-upload-location
    - *upload-images

.installer:
  stage: installer
  script:
    - MOBIAN_ARTIFACTS="rootfs-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}.tar.gz installfs-${ARCH}.tar.gz"
    - *restore-artifacts
    - IMAGE_NAME=mobian-installer-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}-$(date --date="${CI_PIPELINE_CREATED_AT}" +%Y%m%d)
    - zcat "rootfs-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}.tar.gz" | tar2sqfs "rootfs-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}.sqfs" > /dev/null 2>&1
    - debos --scratchsize=8G
      -t architecture:${ARCH}
      -t environment:${MOBIAN_GRAPHICAL_SHELL}
      -t device:${MOBIAN_DEVICE_NAME}
      -t family:${MOBIAN_DEVICE_FAMILY}
      -t filesystem:${MOBIAN_FILESYSTEM}
      -t image:${IMAGE_NAME}
      -t partitiontable:${MOBIAN_PARTITION_TABLE}
      installer.yaml
    - *finish-images
    - MOBIAN_IMAGES="mobian-installer-${MOBIAN_DEVICE_NAME}-${MOBIAN_GRAPHICAL_SHELL}-*"
    - IMAGES_DIR=${IMAGES_CI_ROOT}/$(date --date="${CI_PIPELINE_CREATED_AT}" +%Y%m%d.%H%M)
    - *upload-images
